### PR TITLE
Enhacement of utils.py and interpolator_cli.py

### PR DESCRIPTION
**Pull request by AIManifest**
Enhacement of utils.py and interpolator_cli.py, this PR adds tqdm to the interpolation function and the frame compilation function to show a progress bar while loading. Very minor addition, but works well for my taste!

### CODE REVIEW

**Comment by fitsumreda** [comment]
Can you rebase to head first, and make the changes? Currently, there are more changes (in both files) than just enabling use of `tqdm`.

**Comment by AIManifest** [comment]
> Can you rebase to head first, and make the changes? Currently, there are more changes (in both files) than just enabling use of `tqdm`.

Hey friend! When I open up the pull request tab, it won't let me submit one unless I click on compare across forks, and  when I do that, even with the `base` and `head` being compared, it won't let me create a new PR, which is why I had to fork it and submit the PR that way. If I'm missing something, please advise, so I can follow your instruction!

**Comment by fitsumreda** [comment]
Thanks! See 89c39f2945b452c5a156df334a1aa11e483958dd

**Comment by AIManifest** [comment]
Nice! Thanks for fixing my code also lol!Sent from my iPhoneOn Nov 30, 2022, at 5:18 PM, Fitsum Reda ***@***.***> wrote:﻿
Thanks! See 89c39f2

**Pull request closed without merging**
