### PR TITLE
add Huggingface Spaces Gradio Demo

### PR DESCRIPTION
**Pull request by AK391**
added Web demo on Huggingface Spaces using Gradio

### CODE REVIEW

**Review by fitsumreda — APPROVED** [review]
Thanks!

**Comment by fitsumreda** [comment]
Can you change the hyperlink for 'FILM: Frame Interpolation for Large Motion' from the arXiv abstract page to the project webpage (https://film-net.github.io)?
Thanks!

**Comment by AK391** [comment]
@fitsumreda thanks, sure updated here https://huggingface.co/spaces/akhaliq/frame-interpolation/commit/d24fd05093b43d116779a38624d66e934e98fd02

**Comment by fitsumreda** [comment]
Thanks @AK391 !

**Comment by fitsumreda** [comment]
Hey @AK391 ,
Is it possible to add the existing frame-interpolation Huggingface space to the ECCV 2022 leaderboard that’s being organized by huggingface? I see there that you’re also a member of the organization.

Our frame interpolation paper has been accepted to ECCV, and wanted to see if there is a quick way to participate.

Thanks a lot!

**Comment by AK391** [comment]
@fitsumreda Hi, yes I have transferred the space to the ECCV organization: https://huggingface.co/spaces/ECCV2022/frame-interpolation
also you can join the ECCV organization [here](https://huggingface.co/organizations/ECCV2022/share/kZuMIwRJKOTteDgoueNuPAMUGSnfDjWAGq) to edit the space directly, thanks

**Comment by fitsumreda** [comment]
Thanks @AK391!

**Pull request merged**
